### ISSUE TITLE
[EPIC] - Greenhouse Monitoring & Alerting

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#104]
### Priority

High

### Description

Greenhouse controllers emit the common set of metrics exposed with `controller-runtime`. Additional instrumentation should give more insights into specific error conditions of a controllers reconciliation. Furthermore there are more components of Greenhouse which need to be actively monitoring such as `cors-proxy`, `id-proxy`, and `service-proxy`.

Metrics should be visualised with Plutono Dashboards so that the overall platform, as well individual components health, is easily consumable.

Metrics should be used to define PrometheusAlertRules so that failure conditions can be identified and proactively resolved.

Acceptance criteria:

- [x] Instrumentation of the Controllers #283 
- [x] Instrumentation of Greenhouse Components #286
- [x] Prometheus alerts are defined and can be routed to slack #280 
- [x] Plutono Dashboards are defined #285

**Comment by auhlig** [comment]
Yes, please! 
We should invest at least in the described basic monitoring before onboarding more customers

**Comment by auhlig** [comment]
+ dex controller for authentication related insight
