### ISSUE TITLE
[EPIC] - Supported Kubernetes Versions

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#107]
### Priority

(Medium) I'm annoyed but I'll live

### Description

Helm supports a limited amount of Kubernetes Versions:

As of Helm 3, Helm is assumed to be compatible with n-3 versions of Kubernetes it was compiled against
[[1] Helm Version skew](https://helm.sh/docs/topics/version_skew/)

This matches the Kubernetes versions officially supported [[2] Kubernetes Supported Versions](https://kubernetes.io/releases/version-skew-policy/#supported-versions)

The Greenhouse HelmController should supported the officially supported Kubernetes Versions by Kubernetes & Helm but not more.

Acceptance Criteria:

- [x] Document the decision on which Kubernetes Version to support.
- [ ]  Enduser Docs for which Kubernetes Versions are supported for Greenhouse managed Clusters
- [ ]  Ensure only Clusters with supported Kubernetes Versions can be onboarded
- [ ]  TBD: Stop reconciliation on Clusters running Kubernetes Versions that reached their EOL
- [ ]  Make it visible in the UI, if a Clusters Kubernetes version is going EOL in the next half-year.
- [ ]  (Optional) Deep Link to deprecation warnings shown in DOOP [[3] Constraint Deprecated API Versions](https://github.com/sapcc/helm-charts/blob/master/system/gatekeeper/templates/constrainttemplate-deprecated-api-version.yaml)
