### ISSUE TITLE
[FEAT] -  Plugin Overview: MVP Checklist and Post-MVP Tasks

### ISSUE THREAD

**Issue by ArtieReus** [cloudoperators/greenhouse#152]
### Priority

(Medium) I'm annoyed but I'll live

## MVP
Definition based on:
- the live running implementation (view mode)
- the PR #142 (view, edit and delete mode)

Tasks:

- [x] Remove main tabs and set the existing plugin list view as landing page. Add a DataGridToolbar with a `Add New Plugin` button which would display the available plugins definition from the PR #142 in a panel
- [x] Display a message `It seems that no plugins have been created yet. Do you want to create a new one?` with a button to the available plugins definition (panel) from the PR #142 when no plugins found.
- [x] Available plugins view redesign using a similar template like volta.
- [x] When a plugin definition is selected the form from the PR #142 will displayed in same panel.
- [x] Add to the enabled plugins list an option/button to edit/remove. Remove should have a confirmation dialog.
- [x] New plugin view realocate cancel and create buttons.
- [x] New plugin display error messages on top of the view
- [x] Actually create a secret from a OptionValue with type secret
- [x] Watch Plugins instead of [getting](https://github.com/cloudoperators/greenhouse/blob/main/ui/plugin-admin/src/hooks/useAPI.js#L89), so we get updates without browser reload
- [x] Second confirmation on `Plugin` delete

## Post-MVP

- [ ] Display authentication error message. Right now if no authentication setup is done or an authentication error happens nothing will shown and the enduser sees a black screen.
- [ ] Unify stores
- [ ] Smooth scroll on Panel open within PluginDefinition screens
- [ ] Hide empty entries in Plugin detail view.
- [ ] Use URLstate everywhere
- [ ] Show plugin preset in plugin list if plugin is part of a preset

**Comment by TilmanHaupt** [comment]
Add plugin instantly to list after creating without reload or enforce reload?
