### ISSUE TITLE
[EPIC] - Permission management (TeamRBAC)

### ISSUE THREAD

**Issue by auhlig** [cloudoperators/greenhouse#263]
### Priority

None

### Description

This issue serves as the overarching umbrella for the user story.

Greenhouse enables administrators to manage fine-grained permissions within their organization based on teams for Kubernetes resources and beyond.
The TeamRole and TeamRoleBinding resources implement this behaviour and some issues remain open: #77, #90, #104, #255.

Acceptance criteria:
- [x] #529
- [x] TeamRoles support aggregationRules. See #77 
- [x] TeamRoleBindings support selecting clusters with labelSelector. #90 
- ~~[ ] #388~~
- [ ] TeamRoleBindings support selecting teams with labelSelector. #255
