### ISSUE TITLE
[FEAT] - E2E Plugin Lifecycle

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#419]
### Priority

(Medium) I'm annoyed but I'll live

### Description

There should be an E2E that ensure the Plugin lifecyle is working from deploying the PluginDefinition until the Plugin is deleted again. This should also ensure the Plugin's resources are deleted again.

Documentation on [how to create a PluginDefinition](https://cloudoperators.github.io/greenhouse/docs/user-guides/plugin/development/)

## Tasks:

- [ ] Define a PluginDefinition fixture that acts as an example using the bitnami NGINX chart 
       e.g.: https://cloudoperators.github.io/greenhouse/docs/user-guides/plugin/development/#specify-the-helm-chart-repository
- [ ] Test Setup with a Remote Cluster
   -  differentiate on USE_EXISTING_CLUSTER:
   - false: spin Up "remote" envtest controlplane to test against as in [this example](https://github.com/cloudoperators/greenhouse/blob/main/pkg/controllers/suite_test.go#L39)
   - true: test against remote cluster specified by kubeconfig located at TEST_REMOTE_KUBECONFIG
       - Testrunner can decide wether to run against local KIND or existing cluster
 - [ ] Test the Lifecycle
    - [ ] Deploy PluginDefinition 
    - [ ] Plugin create with a dedicated `.spec.releaseNamespace`
    - [ ] Plugin delete
    - [ ] Check that all the resources are removed from the releaseNamespace
